services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nurtricenter_frontend
    ports:
      - "${FRONTEND_PORT:-8090}:80"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
